version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install --production
      - echo "Verifying Procfile exists..."
      - ls -la
      - cat Procfile
  
  build:
    commands:
      - echo "Build completed on `date`"
  
  post_build:
    commands:
      - echo "Preparing artifact..."
      - echo "Files to be included:"
      - ls -la
      
artifacts:
  files:
    - '**/*'
    - Procfile
    - package.json
    - package-lock.json
    - index.js
  name: application.zip
  type: zip
